project/iClinic/Controllers/BaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iClinic.Models;

namespace iClinic.Controllers
{
    public class BaoCaoController : Controller
    {
        private Entities db = new Entities();

        //
        // GET: /BaoCao/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DoanhThu()
        {
            return View();
        }

        public ActionResult KhamBenh()
        {
            return View();
        }

        public string GetDoanhThuThang(int thang = 1, int nam = 2016)
        {
            double i = db.DbSetHoaDon.Where(h => h.NgayThanhToan.Month == thang && h.NgayThanhToan.Year == nam).Sum(h => (double?)h.TongTien) ?? 0;
            return i.ToString();
        }

        public string GetTongDoanhThuNam(int nam = 2016)
        {
            double i = db.DbSetHoaDon.Where(h => h.NgayThanhToan.Year == nam).Sum(h => (double?)h.TongTien) ?? 0;
            return i.ToString();
        }

        public string GetSoLuotKhamThang(int thang = 1, int nam = 2016)
        {
            int c = db.DbSetPhieuKhamBenh.Count(p => p.NgayKham.Month == thang && p.NgayKham.Year == nam);
            return c.ToString();
        }

        public string GetSoLuotKhamNam(int nam = 2016)
        {
            int c = db.DbSetPhieuKhamBenh.Count(p => p.NgayKham.Year == nam);
            return c.ToString();
        }

        public string GetSoLuotDieuTriThang(int thang = 1, int nam = 2016)
        {
            int c = db.DbSetGiayNhapVien.Count(p => p.NgayNhapVien.Month == thang && p.NgayNhapVien.Year == nam);
            return c.ToString();
        }

        public string GetSoLuotDieuTriNam(int nam = 2016)
        {
            int c = db.DbSetGiayNhapVien.Count(g => g.NgayNhapVien.Year == nam);
            return c.ToString();
        }

        public string GetDoanhThu()
        {
            string data = "[";

            double[] t = new double[13];
            for (int i = 1; i < 13; i++)
            {
                //t[i] = db.DbSetHoaDon.Where(h => h.NgayThanhToan.Month == i && h.NgayThanhToan.Year == 2016).Sum(h => (double?)h.TongTien) ?? 0;
                t[i] = db.DbSetHoaDon.Where(h => h.NgayThanhToan.Month == i && h.NgayThanhToan.Year == DateTime.Today.Year).Sum(h => (double?)h.TongTien) ?? 0;
            }

            for (int i = 1; i < 12; i++)
            {
                data += (t[i] + ",");
            }
            data += (t[12] + "]");

            return data;
        }

        public string GetSoLuotKham()
        {
            string data = "[";

            int[] t = new int[13];
            for (int i = 1; i < 13; i++)
            {
                //t[i] = db.DbSetPhieuKhamBenh.Count(p => p.NgayKham.Month == i && p.NgayKham.Year == 2016);
                t[i] = db.DbSetPhieuKhamBenh.Count(p => p.NgayKham.Month == i && p.NgayKham.Year == DateTime.Now.Year);
            }

            for (int i = 1; i < 12; i++)
            {
                data += (t[i] + ",");
            }
            data += (t[12] + "]");
            
            return data;
        }

        public string GetSoLuotDieuTri()
        {
            string data = "[";

            int[] t = new int[13];
            for (int i = 1; i < 13; i++)
            {
                t[i] = db.DbSetGiayNhapVien.Count(g => g.NgayNhapVien.Month == i && g.NgayNhapVien.Year == DateTime.Today.Year);
                //t[i] = db.DbSetGiayNhapVien.Count(p => p.NgayNhapVien.Month == i && p.NgayNhapVien.Year == 2017);
            }

            for (int i = 1; i < 12; i++)
            {
                data += (t[i] + ",");
            }
            data += (t[12] + "]");

            return data;
        }

    }
}

project/iClinic/Controllers/KhamBenhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iClinic.Models;
using System.Web.Script.Serialization;
using PagedList;

namespace iClinic.Controllers
{
    [Authorize]
    public class KhamBenhController : Controller
    {
        private Entities db = new Entities();
        private Message msg;

        //
        // GET: /KhamBenh/

        //public ActionResult Index()
        //{
        //    var dbsetphieukhambenh = db.DbSetPhieuKhamBenh.Include(p => p.BenhNhan).Include(p => p.BacSi);
        //    return View(dbsetphieukhambenh.ToList());
        //}
        public ActionResult Index(String sortOrder, String currentFilter, String searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParam = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var phieuKB = from s in db.DbSetPhieuKhamBenh select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                phieuKB = phieuKB.Where(s => s.BenhNhan.TenBenhNhan.Contains(searchString));
            }
            switch (sortOrder) { 
                case "name_desc":
                    phieuKB = phieuKB.OrderByDescending(s => s.BenhNhan.TenBenhNhan);
                    break;
                case "Date":
                    phieuKB = phieuKB.OrderBy(s => s.NgayKham);
                    break;
                case "date_desc":
                    phieuKB = phieuKB.OrderByDescending(s => s.NgayKham);
                    break;
                default:
                    phieuKB = phieuKB.OrderBy(s => s.BenhNhan.TenBenhNhan);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(phieuKB.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /KhamBenh/Details/5

        public ActionResult Details(int id = 0)
        {
            PhieuKhamBenh phieukhambenh = db.DbSetPhieuKhamBenh.Find(id);
            if (phieukhambenh == null)
            {
                return HttpNotFound();
            }
            return View(phieukhambenh);
        }

        //
        // GET: /KhamBenh/Create

        public ActionResult Create(int maPhieuKham = 0)
        {
            Message msgThongBao = (Message)TempData["msg"];
            ViewBag.Msg = msgThongBao;

            List<ChiTietDonThuoc> ds = (List<ChiTietDonThuoc>)TempData["dsThuoc"];
            if (ds != null)
            {
                foreach (ChiTietDonThuoc ct in ds)
                {
                    ct.Thuoc = db.DbSetThuoc.Find(ct.ThuocID);
                }
            }
            ViewBag.dsThuoc = ds;

            PhieuKhamBenh pk = db.DbSetPhieuKhamBenh.Find(maPhieuKham);


            ViewBag.BenhNhanSelect = 0;
            ViewBag.DichVuID = db.DbSetDichVu;
            ViewBag.DanhSachThuoc = db.DbSetThuoc;

            if (pk != null)
                return View(pk);

            return View();
        }

        //
        // POST: /KhamBenh/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PhieuKhamBenh phieukhambenh, List<PhieuYeuCauDichVu> dsPhieuYeuCauDichVu)
        {
            if (ModelState.IsValid)
            {
                if (phieukhambenh != null && phieukhambenh.MaPhieuKhamBenh > 0 && dsPhieuYeuCauDichVu.Count > 0)
                {
                    if (dsPhieuYeuCauDichVu != null)
                    {
                        foreach (var item in dsPhieuYeuCauDichVu)
                        {
                            item.PhieuKhamBenhID = phieukhambenh.MaPhieuKhamBenh;
                            item.NgayLap = DateTime.Now;
                            item.ThoiGianThucHien = DateTime.Now;
                            db.DbSetPhieuYeuCauDichVu.Add(item);
                        }
                        db.SaveChanges();
                    }
                    msg = new Message();
                    msg.Type = "success";
                    msg.Title = "Thành công";
                    msg.Content = "Đã lưu dịch vụ khám";
                    TempData["msg"] = msg;
                    //return RedirectToAction("Create", new { id =  });
                    return RedirectToAction("Create");
                }
            }
            if (phieukhambenh.BenhNhan == null)
            {
                msg = new Message();
                msg.Type = "error";
                msg.Title = "Cảnh báo";
                msg.Content = "Chọn bệnh nhân và thêm dịch vụ khám";
                TempData["msg"] = msg;
                return RedirectToAction("Create");                
            }
            //var errors = ModelState.Values.SelectMany(m => m.Errors);
            ViewBag.DichVuID = db.DbSetDichVu;
            ViewBag.DanhSachThuoc = db.DbSetThuoc;
            return View(phieukhambenh);
        }

        [Authorize(Roles = "2")]
        public ActionResult CreateDonThuoc(PhieuKhamBenh phieuKham, List<ChiTietDonThuoc> dsChiTietDonThuoc) 
        {
            TempData["msg"] = msg;
            if (ModelState.IsValid)
            {
                if (phieuKham != null && dsChiTietDonThuoc != null)
                {
                    DonThuoc donThuoc = new DonThuoc {
                        BacSiID = 1,//todo
                        NgayKeDon = DateTime.Now,
                        PhieuKhamBenhID = phieuKham.MaPhieuKhamBenh,
                        TongTien = dsChiTietDonThuoc.Sum(i => i.DonGia * i.SoLuong)
                    };
                    db.DbSetDonThuoc.Add(donThuoc);
                    db.SaveChanges();

                    if (dsChiTietDonThuoc != null)
                    {
                        foreach (var item in dsChiTietDonThuoc)
                        {
                            item.DonThuocID = donThuoc.MaDonThuoc;
                            item.NgayDung = item.Sang + item.Trua + item.Chieu + item.Toi;
                            db.DbSetChiTietDonThuoc.Add(item);
                        }
                        db.SaveChanges();
                    }

                    var dsPhieuCho = db.DbSetPhieuKhamBenhDangCho.Where(m => m.PhieuKhamBenhID == phieuKham.MaPhieuKhamBenh).ToList();
                    if (dsPhieuCho != null)
                    {
                        for (int i = 0; i < dsPhieuCho.Count; i++)
                        {
                            db.DbSetPhieuKhamBenhDangCho.Remove(db.DbSetPhieuKhamBenhDangCho.Find(dsPhieuCho[i].MaPhieuKhamBenhDangCho));
                        }
                    }
                    db.SaveChanges();

                    var dsBNCho = db.DbSetBenhNhanChoKham.Where(m => m.BenhNhanID == phieuKham.BenhNhanID).ToList();
                    if (dsBNCho != null)
                    {
                        for (int i = 0; i < dsBNCho.Count; i++)
                        {
                            db.DbSetBenhNhanChoKham.Remove(db.DbSetBenhNhanChoKham.Find(dsBNCho[i].MaBenhNhan));
                        }
                    }

                    db.SaveChanges();
                    msg = new Message();
                    msg.Type = "success";
                    msg.Title = "Thành công";
                    msg.Content = "Đã lưu đơn thuốc.";
                    TempData["msg"] = msg;
                    TempData["dsThuoc"] = dsChiTietDonThuoc;
                    return RedirectToAction("Create", new { maPhieuKham = phieuKham.MaPhieuKhamBenh });
                }
            }
            var errors = ModelState.Values.SelectMany(m => m.Errors);
            ViewBag.DichVuID = db.DbSetDichVu;
            ViewBag.DanhSachThuoc = db.DbSetThuoc;
            msg = new Message();
            msg.Type = "error";
            msg.Title = "Lỗi";
            msg.Content = "Không thể lưu đơn thuốc.\n" + errors.ToString();
            TempData["msg"] = msg;
            return RedirectToAction("Create");
            //return View(phieuKham);
        }

        //
        // GET: /KhamBenh/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PhieuKhamBenh phieukhambenh = db.DbSetPhieuKhamBenh.Find(id);
            if (phieukhambenh == null)
            {
                return HttpNotFound();
            }
            ViewBag.BenhNhanID = new SelectList(db.DbSetBenhNhan, "MaBenhNhan", "TenBenhNhan", phieukhambenh.BenhNhanID);
            ViewBag.BacSiID = new SelectList(db.DbSetNhanVien, "MaNhanVien", "TenNhanVien", phieukhambenh.BacSiID);
            return View(phieukhambenh);
        }

        //
        // POST: /KhamBenh/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PhieuKhamBenh phieukhambenh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phieukhambenh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BenhNhanID = new SelectList(db.DbSetBenhNhan, "MaBenhNhan", "TenBenhNhan", phieukhambenh.BenhNhanID);
            ViewBag.BacSiID = new SelectList(db.DbSetNhanVien, "MaNhanVien", "TenNhanVien", phieukhambenh.BacSiID);
            return View(phieukhambenh);
        }

        //
        // GET: /KhamBenh/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PhieuKhamBenh phieukhambenh = db.DbSetPhieuKhamBenh.Find(id);
            if (phieukhambenh == null)
            {
                return HttpNotFound();
            }
            return View(phieukhambenh);
        }

        //

project/iClinic/Views/BaoCao/DoanhThu.cshtml
@{
    ViewBag.Title = "Thống kê doanh thu";
}

<h2>DoanhThu</h2>

<div class="row">
    <div class="col-md-6">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Doanh thu theo tháng</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div class="chart">
                    <canvas id="lineChartDoanhThu" style="height:250px"></canvas>
                </div>
            </div>

            <div class="box-footer">
                <button id="btnInDT" style="float: right;" class="btn btn-info"><i class="fa fa-print" aria-hidden="true"></i> In báo cáo</button>
            </div>
        </div>
    </div>   
    <div class="col-md-6">

    </div> 
</div>

<div id="printDT" hidden="hidden">
    <div align="center">
        <p style="font-weight:bold">Phòng khám đa khoa</p>
        <h2>BÁO CÁO DOANH THU NĂM @DateTime.Today.Year</h2>
        <p>&nbsp;</p>
    </div>

    <div style="margin-left: 20px;">
        <p>Tổng doanh thu: <span style="font-weight:bold" id="ten">@Html.Action("GetTongDoanhThuNam", "BaoCao", new { nam = DateTime.Now.Year })</span> VND</p>
    </div>

    <div style="margin-left: 20px; margin-right: 40px; margin-top: 20px;">
        <p>Doanh thu từng tháng</p>
        <table style="border: 1px solid black; border-collapse: collapse;">
            <tr>
                <th style="border: 1px solid black; padding: 15px;">Tháng</th>
                <th style="border: 1px solid black; padding: 15px;">Doanh thu (VND)</th>
            </tr>
            @for (int i = 1; i < 13; i++ )
            {
            <tr>
                <td style="border: 1px solid black;">@i</td>
                <td style="border: 1px solid black;">@Html.Action("GetDoanhThuThang", "BaoCao", new { thang = i, nam = DateTime.Today.Year})</td>
            </tr>
            }
        </table>
    </div>

    <div style="text-align:center; float:right; margin-right: 20px;">
        <p>Ngày @DateTime.Today.Day tháng @DateTime.Today.Month năm @DateTime.Today.Year</p>
        <p>Người lập báo cáo</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>@Html.Action("GetFullName", "Account")</p>
    </div>
</div>

@section Scripts 
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/js/Chart.min.js")"></script>
<script>
  
    var dataDoanhThu = {
        labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        datasets: [
            {
                label: "Doanh thu (VNĐ)",
                fill: false,
                lineTension: 0.1,
                backgroundColor: "rgba(75,192,192,0.4)",
                borderColor: "rgba(75,192,192,1)",
                borderCapStyle: 'butt',
                borderDash: [],
                borderDashOffset: 0.0,
                borderJoinStyle: 'miter',
                pointBorderColor: "rgba(75,192,192,1)",
                pointBackgroundColor: "#fff",
                pointBorderWidth: 1,
                pointHoverRadius: 5,
                pointHoverBackgroundColor: "rgba(75,192,192,1)",
                pointHoverBorderColor: "rgba(220,220,220,1)",
                pointHoverBorderWidth: 2,
                pointRadius: 1,
                pointHitRadius: 10,
                data: @(@Html.Action("GetDoanhThu", "BaoCao")),
                spanGaps: false,
            }
        ]
    };


    var ctx1 = document.getElementById("lineChartDoanhThu");
    var myChart = new Chart(ctx1, {
        type: 'line',
        data: dataDoanhThu,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>

<script type="text/javascript">
    function printDiv(divName) {
        var contents = document.getElementById(divName).innerHTML;
        var frame1 = document.createElement('iframe');
        frame1.name = "frame1";
        frame1.style.position = "absolute";
        frame1.style.top = "-1000000px";
        document.body.appendChild(frame1);
        var frameDoc = frame1.contentWindow ? frame1.contentWindow : frame1.contentDocument.document ? frame1.contentDocument.document : frame1.contentDocument;
        frameDoc.document.open();
        frameDoc.document.write('<html><head><title>DIV Contents</title>');
        frameDoc.document.write('</head><body>');
        frameDoc.document.write(contents);
        frameDoc.document.write('</body></html>');
        frameDoc.document.close();
        setTimeout(function () {
            window.frames["frame1"].focus();
            window.frames["frame1"].print();
            document.body.removeChild(frame1);
        }, 500);
        return false;
    }
</script>

    <script>
        $("#btnInDT").click(function(){
            printDiv('printDT');
        });
    </script>

}

    

project/iClinic/Views/BaoCao/KhamBenh.cshtml
@{
    ViewBag.Title = "Thống kê hoạt động khám bệnh";
}

<h2>DoanhThu</h2>

<div class="row">
    <div class="col-md-6">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Số lượt khám theo tháng</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div class="chart">
                    <canvas id="lineChartSoLuotKham" style="height:250px"></canvas>
                </div>
            </div>

            <div class="box-footer">
                <button id="btnIn" style="float: right;" class="btn btn-info"><i class="fa fa-print" aria-hidden="true"></i> In báo cáo</button>
            </div>
            <!-- /.box-body -->
        </div>
    </div>

    <div class="col-md-6">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Số lượt bệnh nhân điều trị nội trú theo tháng</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div class="chart">
                    <canvas id="lineChartSoLuotDieuTri" style="height:250px"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="printDT" hidden="hidden">
    <div align="center">
        <p style="font-weight:bold">Phòng khám đa khoa</p>
        <h2>BÁO CÁO HOẠT ĐỘNG KHÁM BỆNH NĂM @DateTime.Today.Year</h2>
        <p>&nbsp;</p>
    </div>

    <div style="margin-left: 20px;">
        <p>Tổng số lượt khám: <span style="font-weight:bold" id="ten">@Html.Action("GetSoLuotKhamNam", "BaoCao", new { nam = DateTime.Now.Year })</span></p>
        <p>Tổng số lượt điều trị nội trú: <span style="font-weight:bold" id="ten">@Html.Action("GetSoLuotDieuTriNam", "BaoCao", new { nam = DateTime.Now.Year })</span></p>
    </div>

    <div style="margin-left: 20px; margin-right: 40px; margin-top: 20px;">
        <p>Số lượt khám từng tháng</p>
        <table style="border: 1px solid black; border-collapse: collapse;">
            <tr>
                <th style="border: 1px solid black; padding: 15px;">Tháng</th>
                <th style="border: 1px solid black; padding: 15px;">Lượt khám</th>
            </tr>
            @for (int i = 1; i < 13; i++)
            {
                <tr>
                    <td style="border: 1px solid black;">@i</td>
                    <td style="border: 1px solid black;">@Html.Action("GetSoLuotKhamThang", "BaoCao", new { thang = i, nam = DateTime.Today.Year })</td>
                </tr>
            }
        </table>
    </div>

    <div style="margin-left: 20px; margin-right: 40px; margin-top: 20px;">
        <p>Số lượt điều trị nội trú từng tháng</p>
        <table style="border: 1px solid black; border-collapse: collapse;">
            <tr>
                <th style="border: 1px solid black; padding: 15px;">Tháng</th>
                <th style="border: 1px solid black; padding: 15px;">Lượt điều trị</th>
            </tr>
            @for (int i = 1; i < 13; i++)
            {
                <tr>
                    <td style="border: 1px solid black;">@i</td>
                    <td style="border: 1px solid black;">@Html.Action("GetSoLuotDieuTriThang", "BaoCao", new { thang = i, nam = DateTime.Today.Year })</td>
                </tr>
            }
        </table>
    </div>

    <div style="text-align:center; float:right; margin-right: 20px;">
        <p>Ngày @DateTime.Today.Day tháng @DateTime.Today.Month năm @DateTime.Today.Year</p>
        <p>Người lập báo cáo</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>@Html.Action("GetFullName", "Account")</p>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/js/Chart.min.js")"></script>
    <script>

    var dataSoLuotKham = {
        labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        datasets: [
            {
                label: "Số lượt khám",
                fill: false,
                lineTension: 0.1,
                backgroundColor: "rgba(255, 99, 132, 0.2)",
                borderColor: "rgba(255,99,132,1)",
                borderCapStyle: 'butt',
                borderDash: [],
                borderDashOffset: 0.0,
                borderJoinStyle: 'miter',
                pointBorderColor: "rgba(255,99,132,1)",
                pointBackgroundColor: "#fff",
                pointBorderWidth: 1,
                pointHoverRadius: 5,
                pointHoverBackgroundColor: "rgba(255,99,132,1)",
                pointHoverBorderColor: "rgba(255,99,132,1)",
                pointHoverBorderWidth: 2,
                pointRadius: 1,
                pointHitRadius: 10,
                data: @(@Html.Action("GetSoLuotKham", "BaoCao")),
                spanGaps: false,
            }
        ]
    };

    var dataSoLuotDieuTri = {
        labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        datasets: [
            {
                label: "Số lượt điều trị",
                fill: false,
                lineTension: 0.1,
                backgroundColor: "rgba(255, 99, 132, 0.2)",
                borderColor: "rgba(255,99,132,1)",
                borderCapStyle: 'butt',
                borderDash: [],
                borderDashOffset: 0.0,
                borderJoinStyle: 'miter',
                pointBorderColor: "rgba(255,99,132,1)",
                pointBackgroundColor: "#fff",
                pointBorderWidth: 1,
                pointHoverRadius: 5,
                pointHoverBackgroundColor: "rgba(255,99,132,1)",
                pointHoverBorderColor: "rgba(255,99,132,1)",
                pointHoverBorderWidth: 2,
                pointRadius: 1,
                pointHitRadius: 10,
                data: @(@Html.Action("GetSoLuotDieuTri", "BaoCao")),
                spanGaps: false,
            }
        ]
    };

    var ctx2 = document.getElementById("lineChartSoLuotKham");
    var myChart = new Chart(ctx2, {
        type: 'line',
        data: dataSoLuotKham,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

    var ctx3 = document.getElementById("lineChartSoLuotDieuTri");
    var myChart = new Chart(ctx3, {
        type: 'line',
        data: dataSoLuotDieuTri,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
    </script>

    <script type="text/javascript">
        function printDiv(divName) {
            var contents = document.getElementById(divName).innerHTML;
            var frame1 = document.createElement('iframe');
            frame1.name = "frame1";
            frame1.style.position = "absolute";
            frame1.style.top = "-1000000px";
            document.body.appendChild(frame1);
            var frameDoc = frame1.contentWindow ? frame1.contentWindow : frame1.contentDocument.document ? frame1.contentDocument.document : frame1.contentDocument;
            frameDoc.document.open();
            frameDoc.document.write('<html><head><title>DIV Contents</title>');
            frameDoc.document.write('</head><body>');
            frameDoc.document.write(contents);
            frameDoc.document.write('</body></html>');
            frameDoc.document.close();
            setTimeout(function () {
                window.frames["frame1"].focus();
                window.frames["frame1"].print();
                document.body.removeChild(frame1);
            }, 500);
            return false;
        }
    </script>

    <script>
        $("#btnIn").click(function(){
            printDiv('printDT');
        });
    </script>

}